local gameinfo = {
    waveInfo = {
        easy = {
            { enemies = { basic = 4,}, reward = 25 },
            { enemies = { basic = 5, fast = 1 }, reward = 25 },
            { enemies = { basic = 7, fast = 2, tank = 1 }, reward = 25 },
            { enemies = { basic = 10, fast = 4, tank = 2 }, reward = 25 },
            { enemies = { elite = 1, basic = 3, fast = 2 }, reward = 25 },
            { enemies = { basic = 6, fast = 3, tank = 2 }, reward = 25 },
            { enemies = { basic = 5, fast = 4, elite = 1 }, reward = 25 },
            { enemies = { basic = 7, fast = 3, tank = 3 }, reward = 25 },
            { enemies = { basic = 6, fast = 4, elite = 2 }, reward = 25 },
            { enemies = { boss_easy = 1 }, reward = 100 }
        },

        medium = {
            { enemies = { basic = 5, fast = 2 }, reward = 30 },
            { enemies = { basic = 7, fast = 3 }, reward = 30 },
            { enemies = { basic = 8, fast = 3, tank = 1 }, reward = 30 },
            { enemies = { basic = 10, fast = 4, tank = 2 }, reward = 30 },
            { enemies = { elite = 2, basic = 5, fast = 2 }, reward = 30 },
            { enemies = { basic = 7, fast = 4, tank = 2 }, reward = 30 },
            { enemies = { basic = 6, fast = 5, elite = 1 }, reward = 30 },
            { enemies = { basic = 8, fast = 4, tank = 3 }, reward = 30 },
            { enemies = { basic = 7, fast = 5, elite = 2 }, reward = 30 },
            { enemies = { boss_easy = 1 }, reward = 150 },
            { enemies = { basic = 8, fast = 5, tank = 4 }, reward = 30 },
            { enemies = { basic = 7, fast = 6, elite = 2 }, reward = 30 },
            { enemies = { basic = 9, fast = 5, tank = 4, elite = 1 }, reward = 30 },
            { enemies = { basic = 8, fast = 6, elite = 3 }, reward = 30 },
            { enemies = { boss_medium = 1, fast = 5 }, reward = 200 }
        },

        hard = {
            { enemies = { basic = 5, fast = 3 }, reward = 40 },
            { enemies = { basic = 6, fast = 4, tank = 1 }, reward = 40 },
            { enemies = { basic = 7, fast = 4, tank = 2 }, reward = 40 },
            { enemies = { basic = 6, fast = 5, elite = 1 }, reward = 40 },
            { enemies = { boss_easy = 1 }, reward = 200 },
            { enemies = { basic = 8, fast = 5, tank = 3, elite = 1 }, reward = 40 },
            { enemies = { basic = 7, fast = 6, tank = 4, elite = 2 }, reward = 40 },
            { enemies = { basic = 9, fast = 6, tank = 4, elite = 2 }, reward = 40 },
            { enemies = { basic = 8, fast = 7, tank = 5, elite = 3 }, reward = 40 },
            { enemies = { boss_medium = 1, fast = 5 }, reward = 250 },
            { enemies = { basic = 10, fast = 7, tank = 5, elite = 3 }, reward = 40 },
            { enemies = { basic = 9, fast = 8, tank = 6, elite = 4 }, reward = 40 },
            { enemies = { basic = 11, fast = 8, tank = 6, elite = 4 }, reward = 40 },
            { enemies = { basic = 10, fast = 9, tank = 7, elite = 5 }, reward = 40 },
            { enemies = { boss_hard = 1 }, reward = 300 },
            { enemies = { basic = 12, fast = 9, tank = 7, elite = 5 }, reward = 40 },
            { enemies = { basic = 11, fast = 10, tank = 8, elite = 6 }, reward = 40 },
            { enemies = { basic = 13, fast = 10, tank = 8, elite = 6 }, reward = 40 },
            { enemies = { basic = 12, fast = 11, tank = 9, elite = 7 }, reward = 40 },
            { enemies = { boss_hard = 1, fast = 5, tank = 10 }, reward = 400 }
        },

        endless = {
            { enemies = { basic = 3 }, reward = 10 },
            { enemies = { basic = 5 }, reward = 10 },
            { enemies = { basic = 7 }, reward = 10 },
            { enemies = { basic = 10 }, reward = 10 },
            { enemies = { basic = 10, fast = 3 }, reward = 15 },
            { enemies = { basic = 15, fast = 5 }, reward = 10 },
            { enemies = { basic = 15, fast = 7 }, reward = 10 },
            { enemies = { basic = 5, fast = 15 }, reward = 10 },
            { enemies = { tank = 3, basic = 10 }, reward = 10 },
            { enemies = { boss_easy = 1, tank = 5 }, reward = 40 },
            { enemies = { basic = 10, fast = 10, tank = 5 }, reward = 20 },
            { enemies = { basic = 12, fast = 12, tank = 7 }, reward = 20 },
            { enemies = { basic = 5, fast = 15, tank = 15 }, reward = 20 },
            { enemies = { fast = 25, tank = 25 }, reward = 20 },
            { enemies = { fast = 10, tank = 10, elite = 5 }, reward = 30 },
            { enemies = { fast = 15, tank = 5, elite = 10 }, reward = 20 },
            { enemies = { fast = 10, tank = 5, elite = 15 }, reward = 20 },
            { enemies = { fast = 15, tank = 5, elite = 10 }, reward = 20 },
            { enemies = { basic = 25, elite = 25 }, reward = 20 },
            { enemies = { boss_medium = 1, elite = 10, fast = 10 }, reward = 80 },
            { enemies = { boss_easy = 1, tank = 10, fast = 10, basic = 10 }, reward = 40 },
            { enemies = { boss_easy = 1, tank = 15, fast = 15, basic = 15 }, reward = 40 },
            { enemies = { boss_easy = 1, tank = 15, elite = 10 }, reward = 40 },
            { enemies = { boss_easy = 3, elite = 10 }, reward = 40 },
            { enemies = { boss_easy = 5, elite = 10, assault = 3 }, reward = 60 },
            { enemies = { elite = 15, assault = 10, fast = 15 }, reward = 40 },
            { enemies = { assault = 15, fast = 25 }, reward = 40 },
            { enemies = { assault = 10, basic = 40, elite = 15 }, reward = 40 },
            { enemies = { basic = 75 }, reward = 40 },
            { enemies = { boss_hard = 1, assault = 20, boss_easy = 5 }, reward = 160 },
            { enemies = { boss_easy = 10, assault = 15 }, reward = 80 },
            { enemies = { boss_easy = 13, fast = 30 }, reward = 80 },
            { enemies = { boss_medium = 1, boss_easy = 10 }, reward = 80 },
            { enemies = { fast = 75 }, reward = 80 },
            { enemies = { boss_medium = 3, healer = 5, tank = 10 }, reward = 120 },
            { enemies = { healer = 10, tank = 25, elite = 10, assault = 5 }, reward = 80 },
            { enemies = { healer = 15, tank = 30, elite = 15, assault = 10 }, reward = 80 },
            { enemies = { healer = 20, boss_easy = 20 }, reward = 80 },
            { enemies = { healer = 10, boss_medium = 10 }, reward = 80 },
            { enemies = { boss_hard = 3, boss_medium = 10, healer = 10, assault = 7 }, reward = 320 },
        },

        bossrush = {
            { enemies = { boss_easy = 1 }, reward = 25 },
            { enemies = { boss_medium = 1 }, reward = 50 },
            { enemies = { boss_hard = 1 }, reward = 75 },
            { enemies = { boss_summoner = 1 }, reward = 100 },
            { enemies = { boss_sniper = 1 }, reward = 120 },
            { enemies = { boss_phantom = 1 }, reward = 150 },
            { enemies = { finalBoss_Phase1 = 1 }, reward = 200 },
            { enemies = { boss_final_phase2 = 1 }, reward = 300 },  -- 修正：类型名改为小写，与enemyTypesBase中的键一致
        },
    },
}

return gameinfo